### ISSUE TITLE
laravel 5 friendly teamwork integrations

### ISSUE THREAD

**Issue by michaeljhopkins** [rossedman/teamwork#1]
not an issue. just wanted to say this is killer and something I had been wanting to do but found their api a little tricky to work with. thanks for the time and doing it open source!

**Comment by rossedman** [comment]
@michaeljhopkins Thanks a lot. I'm actually finishing out the 1.0.0 release in the next week or so! I hope you put it to good use. I've done a lot of Git / Webhook integrations with Teamwork and found I wanted something more robust. I'm also doing a Ruby Gem as well.
