### ISSUE TITLE
Create milestone in project

### ISSUE THREAD

**Issue by cmbirk** [rossedman/teamwork#2]
I'm not able to figure out how to do this or if it's even been implemented.  I've tried:

```
Teamwork::project($projectId)->milestone()->create([
... 
]); // 'Call to undefined method Rossedman\Teamwork\Project::milestone()'
```

```
Teamwork::project($projectId)->milestones()->create() //Call to member function on non-object
```

```
Teamwork::milestone()->create([
...
'project-id' => $projectId
...
]); // ... 400 [reason phrase] Bad Request
```

Is there a way to do this that I'm missing or does this still need to be implemented?

**Comment by cmbirk** [comment]
This is in the documentation.  I apologize for missing it :(

**Comment by cmbirk** [comment]
Re-opening.  It looks like Project::createMilestone hasn't been implemented.

**Comment by cmbirk** [comment]
Here's the code that needs to be added to `Project.php`.  I will open a pull request when I can.

```
/**
     * Create milestone associated with this project
     * POST /projects/{project_id}/milestones.json
     *
     * @return mixed
     */
    public function createMilestone($args) {
        return $this->client->post("$this->endpoint/$this->id/milestones", ['milestone' => $args])->response();
    }
```

**Comment by cmbirk** [comment]
I've opened a pull request here:

https://github.com/rossedman/teamwork/pull/3

**Comment by rossedman** [comment]
:+1: Looks good. Thanks a lot.
